version: '3'
services: 

  influxdb:
    image: influxdb:1.4-alpine
    container_name: influxdb
    ports:
      - "8086:8086"
    env_file:
      - 'env.influxdb'

  grafana:
    image: grafana/grafana:4.6.3
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=natel-influx-admin-panel
      - GF_SECURITY_ADMIN_PASSWORD=1admin!
