- hosts: all
  become: true
  become_method: sudo
  vars:
    username: vagrant
  roles:
    - { role: angstwad.docker_ubuntu }
    - { role: geerlingguy.git }
  tasks:
    - name: Avoid using sudo when using docker command
      command: usermod -aG docker {{username}}
    - name: Installs vim package
      apt: pkg=vim state=installed update_cache=true
