- hosts: all
  become: true
  become_method: sudo
  vars:
    username: vagrant
  roles:
    - { role: angstwad.docker_ubuntu,
      docker_opts: "-H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock --registry-mirror=https://registry.mirror:5000"
    }
    - role: geerlingguy.git
  tasks:
    - name: Avoid using sudo when using docker command
      command: usermod -aG docker {{username}}
    - name: Installs vim package
      apt: pkg=vim state=installed update_cache=true
    - file: path=/etc/docker/certs.d/blue.sky state=directory mode=0755
    - name: Docker private registry CA certificate - docker daemon config
      copy: src=files/blue.sky_certs/domain.crt dest=/etc/docker/certs.d/blue.sky/ca.crt
    - file: path=/opt/docker_volumes/registry/blue.sky/certs owner={{username}} group={{username}} state=directory mode=0775
    - name: Docker private registry CA certificate - private registry config
      copy: src=files/blue.sky_certs/domain.crt dest=/opt/docker_volumes/registry/blue.sky/certs/domain.crt
    - name: Docker private registry key - private registry config
      copy: src=files/blue.sky_certs/domain.key dest=/opt/docker_volumes/registry/blue.sky/certs/domain.key
    - name: Configure hosts
      lineinfile:
        dest: /etc/hosts
        line: "{{ item.line }}"
      with_items:
        - { line: ''}
        - { line: '172.17.0.1      blue.sky' }
