version: '3'
services:

  influxdb:
    image: influxdb:1.4-alpine
    container_name: influxdb
    ports:
      - "45386:8086"
    env_file:
      - 'env.influxdb'

  grafana:
    image: grafana/grafana:4.6.3
    container_name: grafana
    ports:
      - "45381:3000"
    environment:
      - GF_INSTALL_PLUGINS=natel-influx-admin-panel
      - GF_SECURITY_ADMIN_USER=rango
      - GF_SECURITY_ADMIN_PASSWORD=1admin!
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
