version: '2'
services:


  git-server:
    image: casadocker/git-server:16.06.05
    container_name: git-server
    restart: always
    ports:
      - "2224:22"
    volumes:
      - git-server-data:/opt/git/repositories

volumes:
  git-server-data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
