version: '2'
services:

  # Nexus maven repository
  # sonatype.com/download-oss-sonatype
  nexus:
    image: sonatype/nexus:2.13.0-01
    container_name: nexus
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/sonatype-work

  # Raw git server
  # https://github.com/tecris/dockerfiles/tree/master/git-server
  git-server:
    build: ./git-server
    image: casadocker/git-server:16.06.15
    container_name: git-server
    restart: always
    ports:
      - "2224:22"
      - "9418:9418"
    volumes:
      - git-server-data:/opt/git/repositories

  # Jenkins with custom modifications
  # https://github.com/tecris/dockerfiles/tree/master/jenkins
  jenkins:
    image: casadocker/jenkins:2.60.2
    container_name: jenkins
    restart: always
    volumes:
      - jenkins-data:/var/jenkins_home
      - iv-tests-data:/opt/jenkins/iv-e2e-java/site/serenity/
    ports:
      - "8080:8080"
    extra_hosts:
      - "docker.host:${DOCKER_IP}"
      - "cloud.atlas:${DOCKER_IP}"

  # used to serve E2E test reports
  nginx:
    build: ./nginx
    image: casadocker/nginx:16.06.19
    container_name: nginx
    restart: always
    volumes:
      - iv-tests-data:/usr/share/nginx/html/iv-tests
    ports:
      - "8002:80"

  # docker private registry
  bluesky-registry:
    image: registry:2
    container_name: blue.sky
    restart: always
    ports:
      - 443:5000
    environment:
      # how to override configuration
      # https://docs.docker.com/registry/configuration/#override-specific-configuration-options
      # https://github.com/docker/distribution/blob/master/docs/configuration.md
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    volumes:
      - /opt/docker_volumes/registry/blue.sky/data:/var/lib/registry
      - /opt/docker_volumes/registry/blue.sky/certs:/certs

  # Selenium Grid hub
  selhub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - 4444:4444

  # Selenium Grid firefox node
  nodeff:
    image: selenium/node-firefox
    container_name: selenium-firefox
    ports:
      - 5900
    extra_hosts:
      - "docker.host:${DOCKER_IP}"
    environment:
      - HUB_PORT_4444_TCP_ADDR=selhub
      - HUB_PORT_4444_TCP_PORT=4444

    depends_on:
      - selhub

  # database used by sonar
  sonar-db:
    image: postgres:9.5
    container_name: sonar-db
    environment:
      - POSTGRES_DB=sonar
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar

  # sonarqube.org - quality management platform
  sonar:
    image: sonarqube:5.4-alpine
    container_name: sonar
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonar
    depends_on:
      - sonar-db

volumes:
  iv-tests-data:
  nexus-data:
  git-server-data:
  jenkins-data:
